-- SQL commands to create door lock activity logging table
CREATE TABLE IF NOT EXISTS public.door_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    profile_name text NOT NULL,
    action text NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.door_logs ENABLE ROW LEVEL SECURITY;

-- Create policies for door_logs
CREATE POLICY "Users can view logs in their own account"
    ON public.door_logs FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert logs in their own account"
    ON public.door_logs FOR INSERT
    WITH CHECK (auth.uid() = user_id);
